# kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf -o yaml > jwt-secret.yaml
apiVersion: v1
data:
  JWT_KEY: YXNkZg==
kind: Secret
metadata:
  creationTimestamp: "2023-08-01T14:16:38Z"
  name: jwt-secret
  namespace: default
  resourceVersion: "235107"
  uid: 0ebb05f8-8d5b-4a7a-819f-c783bb8a2496
type: Opaque
