apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:    
    - image: blog/client
      context: client
      sync:
        manual:
          # if changes are made to *.js files, Skaffold will
          # copy the file directly inside the Pod
          # If changes are made to something that does not match
          # the regexp, then Skaffold will rebuild the container
          # and deploy it again.
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: blog/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: blog/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: blog/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: blog/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: blog/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  