name: deploy-auth

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd ticketing/auth && docker build -t giammarcoboscaro/ticketing-auth .
      - run: docker push giammarcoboscaro/ticketing-auth
