name: deploy-tickets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ticketing/tickets/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.x'
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: npm install
        working-directory: ./ticketing/tickets
      - run: npm run build
        working-directory: ./ticketing/tickets
      - run: docker build -t giammarcoboscaro/ticketing-tickets .
        working-directory: ./ticketing/tickets
      - run: docker push giammarcoboscaro/ticketing-tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save udemy-microservices-ticketing-app
      - run: kubectl rollout restart deployment tickets-deploy
