name: deploy-client

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ticketing/client/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd ticketing/client && docker build -t giammarcoboscaro/ticketing-client .
      - run: docker push giammarcoboscaro/ticketing-client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save udemy-microservices-ticketing-app
      - run: kubectl rollout restart deployment client-deploy
