name: tests-auth

on:
  pull_request:
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.x'
      - run: npm install
        working-directory: ./ticketing/auth
      - run: npm run test:ci
        working-directory: ./ticketing/auth
