name: tests-payments

on:
  pull_request:
    paths:
      - 'ticketing/payments/**'

env:
  STRIPE_KEY: sk_test_51I57b5FCYxFKFs25CSkBWmnzYFHa3V8oclrAhN7KjADRCWSzdKUbwVKr6BgTfjPvynVgCjSgdAc5RtLzaAk4b8Zq00asxCYVwo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ticketing/payments && npm install && npm run test:ci
