name: tests-auth

on:
  pull_request:
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ticketing/auth && npm install && npm run test:ci
